sudo: yes
dist: bionic
language: python

python:
- '3.7'

services:
  - postgresql

install:
- pip install tox-travis

before_script:
- createdb library-crud-test

script:
  - tox

env:
  global:
   - PGUSER=postgres
   - PGPORT=5432
   - PGHOST=localhost
