
version: '3.3'
services:
  flask-app:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.test
    environment:
      - DB_HOST=db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env.test
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file: ./.env.test

volumes:
    postgres_data:
    flask-app:
    pgadmin-data:
