
version: '3.3'
services:
  flask-app:
    build: .
    command: tox
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.test
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file: ./.env.test

volumes:
    postgres_data:
    flask-app:
